CREATE TABLE ROUTINE_EXERCISE (
	codRoutine INTEGER,
	codExercise INTEGER,
	CONSTRAINT ROUTINE_EXERCISE_PK PRIMARY KEY (codRoutine,codExercise)
	CONSTRAINT ROUTINE_EXERCISE_FK1 FOREIGN KEY (codRoutine) REFERENCES ROUTINE,
	CONSTRAINT ROUTINE_EXERCISE_FK2 FOREIGN KEY (codExercise) REFERENCES EXERCISE
);
